version: '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - DB_USER=${MYSQL_USER}
        - DB_PASSWORD=${MYSQL_PASSWORD}
        - DB_NAME=${DB_NAME}
    restart: always
    volumes:
      - v_mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - v_wordpress:/var/www/wordpress
    env_file: .env
    networks:
      - inception

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - v_wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress

volumes:
  v_wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wordpress
  v_mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/mariadb

networks:
  inception:
    driver: bridge